name: hawkeye_wifi_viewer
description: Hawkeye WiFi Viewer
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  network_info_plus: ^6.1.0
  permission_handler: ^11.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/HawkEyewifi.png"
  adaptive_icon_background: "#1a1a2e"
  adaptive_icon_foreground: "assets/HawkEyewifi.png"

flutter:
  uses-material-design: true
  assets:
    - assets/HawkEyewifi.png
